<?php
/**
 * IntegrationKindsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2.0 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Wodby\Api\Test\Api;

use \Wodby\Api\Configuration;
use \Wodby\Api\ApiException;
use \Wodby\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IntegrationKindsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IntegrationKindsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for integrationKindsIdDatabaseMachineTypesGet
     *
     * List database machine types.
     *
     */
    public function testIntegrationKindsIdDatabaseMachineTypesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for integrationKindsIdDatabaseRegionsGet
     *
     * List database regions.
     *
     */
    public function testIntegrationKindsIdDatabaseRegionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for integrationKindsIdDatabaseSettingsGet
     *
     * Get database settings.
     *
     */
    public function testIntegrationKindsIdDatabaseSettingsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for integrationKindsIdDatabaseTypesGet
     *
     * List database types.
     *
     */
    public function testIntegrationKindsIdDatabaseTypesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for integrationKindsIdDatabaseVersionsGet
     *
     * List database versions.
     *
     */
    public function testIntegrationKindsIdDatabaseVersionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
