<?php
/**
 * ServicesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Wodby\Api\Test\Api;

use \Wodby\Api\Configuration;
use \Wodby\Api\ApiException;
use \Wodby\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getService
     *
     * Get service.
     *
     */
    public function testGetService()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServiceByName
     *
     * Get service by name.
     *
     */
    public function testGetServiceByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServiceRevision
     *
     * Get service revision.
     *
     */
    public function testGetServiceRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for importServices
     *
     * Import services from Git.
     *
     */
    public function testImportServices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listServiceLinkCandidates
     *
     * List service link candidates.
     *
     */
    public function testListServiceLinkCandidates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listServices
     *
     * List services.
     *
     */
    public function testListServices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateServiceSettings
     *
     * Update service settings.
     *
     */
    public function testUpdateServiceSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
