<?php
/**
 * AppBuild
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2.0 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;

use \ArrayAccess;
use \Wodby\Api\ObjectSerializer;

/**
 * AppBuild Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppBuild implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppBuild';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'number' => 'int',
        'status' => 'string',
        'app_instance_id' => 'int',
        'app_service_id' => 'int',
        'git_ref_type' => 'string',
        'git_ref' => 'string',
        'commit_hash' => 'string',
        'commit_message' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'started_at' => '\DateTime',
        'ended_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'number' => null,
        'status' => null,
        'app_instance_id' => null,
        'app_service_id' => null,
        'git_ref_type' => null,
        'git_ref' => null,
        'commit_hash' => null,
        'commit_message' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'started_at' => 'date-time',
        'ended_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'number' => false,
        'status' => false,
        'app_instance_id' => false,
        'app_service_id' => false,
        'git_ref_type' => false,
        'git_ref' => false,
        'commit_hash' => false,
        'commit_message' => false,
        'created_at' => false,
        'updated_at' => false,
        'started_at' => true,
        'ended_at' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'number' => 'number',
        'status' => 'status',
        'app_instance_id' => 'appInstanceId',
        'app_service_id' => 'appServiceId',
        'git_ref_type' => 'gitRefType',
        'git_ref' => 'gitRef',
        'commit_hash' => 'commitHash',
        'commit_message' => 'commitMessage',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'started_at' => 'startedAt',
        'ended_at' => 'endedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'number' => 'setNumber',
        'status' => 'setStatus',
        'app_instance_id' => 'setAppInstanceId',
        'app_service_id' => 'setAppServiceId',
        'git_ref_type' => 'setGitRefType',
        'git_ref' => 'setGitRef',
        'commit_hash' => 'setCommitHash',
        'commit_message' => 'setCommitMessage',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'started_at' => 'setStartedAt',
        'ended_at' => 'setEndedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'number' => 'getNumber',
        'status' => 'getStatus',
        'app_instance_id' => 'getAppInstanceId',
        'app_service_id' => 'getAppServiceId',
        'git_ref_type' => 'getGitRefType',
        'git_ref' => 'getGitRef',
        'commit_hash' => 'getCommitHash',
        'commit_message' => 'getCommitMessage',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'started_at' => 'getStartedAt',
        'ended_at' => 'getEndedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('app_instance_id', $data ?? [], null);
        $this->setIfExists('app_service_id', $data ?? [], null);
        $this->setIfExists('git_ref_type', $data ?? [], null);
        $this->setIfExists('git_ref', $data ?? [], null);
        $this->setIfExists('commit_hash', $data ?? [], null);
        $this->setIfExists('commit_message', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('started_at', $data ?? [], null);
        $this->setIfExists('ended_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['app_instance_id'] === null) {
            $invalidProperties[] = "'app_instance_id' can't be null";
        }
        if ($this->container['app_service_id'] === null) {
            $invalidProperties[] = "'app_service_id' can't be null";
        }
        if ($this->container['git_ref_type'] === null) {
            $invalidProperties[] = "'git_ref_type' can't be null";
        }
        if ($this->container['git_ref'] === null) {
            $invalidProperties[] = "'git_ref' can't be null";
        }
        if ($this->container['commit_hash'] === null) {
            $invalidProperties[] = "'commit_hash' can't be null";
        }
        if ($this->container['commit_message'] === null) {
            $invalidProperties[] = "'commit_message' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets number
     *
     * @return int
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param int $number number
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            throw new \InvalidArgumentException('non-nullable number cannot be null');
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets app_instance_id
     *
     * @return int
     */
    public function getAppInstanceId()
    {
        return $this->container['app_instance_id'];
    }

    /**
     * Sets app_instance_id
     *
     * @param int $app_instance_id app_instance_id
     *
     * @return self
     */
    public function setAppInstanceId($app_instance_id)
    {
        if (is_null($app_instance_id)) {
            throw new \InvalidArgumentException('non-nullable app_instance_id cannot be null');
        }
        $this->container['app_instance_id'] = $app_instance_id;

        return $this;
    }

    /**
     * Gets app_service_id
     *
     * @return int
     */
    public function getAppServiceId()
    {
        return $this->container['app_service_id'];
    }

    /**
     * Sets app_service_id
     *
     * @param int $app_service_id app_service_id
     *
     * @return self
     */
    public function setAppServiceId($app_service_id)
    {
        if (is_null($app_service_id)) {
            throw new \InvalidArgumentException('non-nullable app_service_id cannot be null');
        }
        $this->container['app_service_id'] = $app_service_id;

        return $this;
    }

    /**
     * Gets git_ref_type
     *
     * @return string
     */
    public function getGitRefType()
    {
        return $this->container['git_ref_type'];
    }

    /**
     * Sets git_ref_type
     *
     * @param string $git_ref_type git_ref_type
     *
     * @return self
     */
    public function setGitRefType($git_ref_type)
    {
        if (is_null($git_ref_type)) {
            throw new \InvalidArgumentException('non-nullable git_ref_type cannot be null');
        }
        $this->container['git_ref_type'] = $git_ref_type;

        return $this;
    }

    /**
     * Gets git_ref
     *
     * @return string
     */
    public function getGitRef()
    {
        return $this->container['git_ref'];
    }

    /**
     * Sets git_ref
     *
     * @param string $git_ref git_ref
     *
     * @return self
     */
    public function setGitRef($git_ref)
    {
        if (is_null($git_ref)) {
            throw new \InvalidArgumentException('non-nullable git_ref cannot be null');
        }
        $this->container['git_ref'] = $git_ref;

        return $this;
    }

    /**
     * Gets commit_hash
     *
     * @return string
     */
    public function getCommitHash()
    {
        return $this->container['commit_hash'];
    }

    /**
     * Sets commit_hash
     *
     * @param string $commit_hash commit_hash
     *
     * @return self
     */
    public function setCommitHash($commit_hash)
    {
        if (is_null($commit_hash)) {
            throw new \InvalidArgumentException('non-nullable commit_hash cannot be null');
        }
        $this->container['commit_hash'] = $commit_hash;

        return $this;
    }

    /**
     * Gets commit_message
     *
     * @return string
     */
    public function getCommitMessage()
    {
        return $this->container['commit_message'];
    }

    /**
     * Sets commit_message
     *
     * @param string $commit_message commit_message
     *
     * @return self
     */
    public function setCommitMessage($commit_message)
    {
        if (is_null($commit_message)) {
            throw new \InvalidArgumentException('non-nullable commit_message cannot be null');
        }
        $this->container['commit_message'] = $commit_message;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets started_at
     *
     * @return \DateTime|null
     */
    public function getStartedAt()
    {
        return $this->container['started_at'];
    }

    /**
     * Sets started_at
     *
     * @param \DateTime|null $started_at started_at
     *
     * @return self
     */
    public function setStartedAt($started_at)
    {
        if (is_null($started_at)) {
            array_push($this->openAPINullablesSetToNull, 'started_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('started_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['started_at'] = $started_at;

        return $this;
    }

    /**
     * Gets ended_at
     *
     * @return \DateTime|null
     */
    public function getEndedAt()
    {
        return $this->container['ended_at'];
    }

    /**
     * Sets ended_at
     *
     * @param \DateTime|null $ended_at ended_at
     *
     * @return self
     */
    public function setEndedAt($ended_at)
    {
        if (is_null($ended_at)) {
            array_push($this->openAPINullablesSetToNull, 'ended_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ended_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ended_at'] = $ended_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


