<?php
/**
 * AppInstanceCICDSettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;

use \ArrayAccess;
use \Wodby\Api\ObjectSerializer;

/**
 * AppInstanceCICDSettings Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppInstanceCICDSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppInstanceCICDSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'app_instance_id' => 'int',
        'ci_integration_id' => 'int',
        'registry_integration_id' => 'int',
        'registry_repository' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'app_instance_id' => null,
        'ci_integration_id' => null,
        'registry_integration_id' => null,
        'registry_repository' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'app_instance_id' => false,
        'ci_integration_id' => false,
        'registry_integration_id' => false,
        'registry_repository' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'app_instance_id' => 'appInstanceId',
        'ci_integration_id' => 'ciIntegrationId',
        'registry_integration_id' => 'registryIntegrationId',
        'registry_repository' => 'registryRepository'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'app_instance_id' => 'setAppInstanceId',
        'ci_integration_id' => 'setCiIntegrationId',
        'registry_integration_id' => 'setRegistryIntegrationId',
        'registry_repository' => 'setRegistryRepository'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'app_instance_id' => 'getAppInstanceId',
        'ci_integration_id' => 'getCiIntegrationId',
        'registry_integration_id' => 'getRegistryIntegrationId',
        'registry_repository' => 'getRegistryRepository'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('app_instance_id', $data ?? [], null);
        $this->setIfExists('ci_integration_id', $data ?? [], null);
        $this->setIfExists('registry_integration_id', $data ?? [], null);
        $this->setIfExists('registry_repository', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['app_instance_id'] === null) {
            $invalidProperties[] = "'app_instance_id' can't be null";
        }
        if ($this->container['ci_integration_id'] === null) {
            $invalidProperties[] = "'ci_integration_id' can't be null";
        }
        if ($this->container['registry_integration_id'] === null) {
            $invalidProperties[] = "'registry_integration_id' can't be null";
        }
        if ($this->container['registry_repository'] === null) {
            $invalidProperties[] = "'registry_repository' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets app_instance_id
     *
     * @return int
     */
    public function getAppInstanceId()
    {
        return $this->container['app_instance_id'];
    }

    /**
     * Sets app_instance_id
     *
     * @param int $app_instance_id app_instance_id
     *
     * @return self
     */
    public function setAppInstanceId($app_instance_id)
    {
        if (is_null($app_instance_id)) {
            throw new \InvalidArgumentException('non-nullable app_instance_id cannot be null');
        }
        $this->container['app_instance_id'] = $app_instance_id;

        return $this;
    }

    /**
     * Gets ci_integration_id
     *
     * @return int
     */
    public function getCiIntegrationId()
    {
        return $this->container['ci_integration_id'];
    }

    /**
     * Sets ci_integration_id
     *
     * @param int $ci_integration_id Effective CI integration ID. Zero selects the built-in Wodby CI service.
     *
     * @return self
     */
    public function setCiIntegrationId($ci_integration_id)
    {
        if (is_null($ci_integration_id)) {
            throw new \InvalidArgumentException('non-nullable ci_integration_id cannot be null');
        }
        $this->container['ci_integration_id'] = $ci_integration_id;

        return $this;
    }

    /**
     * Gets registry_integration_id
     *
     * @return int
     */
    public function getRegistryIntegrationId()
    {
        return $this->container['registry_integration_id'];
    }

    /**
     * Sets registry_integration_id
     *
     * @param int $registry_integration_id Effective registry integration ID. Zero selects the built-in Wodby registry service.
     *
     * @return self
     */
    public function setRegistryIntegrationId($registry_integration_id)
    {
        if (is_null($registry_integration_id)) {
            throw new \InvalidArgumentException('non-nullable registry_integration_id cannot be null');
        }
        $this->container['registry_integration_id'] = $registry_integration_id;

        return $this;
    }

    /**
     * Gets registry_repository
     *
     * @return string
     */
    public function getRegistryRepository()
    {
        return $this->container['registry_repository'];
    }

    /**
     * Sets registry_repository
     *
     * @param string $registry_repository registry_repository
     *
     * @return self
     */
    public function setRegistryRepository($registry_repository)
    {
        if (is_null($registry_repository)) {
            throw new \InvalidArgumentException('non-nullable registry_repository cannot be null');
        }
        $this->container['registry_repository'] = $registry_repository;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


