<?php
/**
 * AppRouteSettingSource
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;
use \Wodby\Api\ObjectSerializer;

/**
 * AppRouteSettingSource Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppRouteSettingSource
{
    /**
     * Possible values of this enum
     */
    public const APP_DEFAULT = 'APP_DEFAULT';

    public const SERVICE_DEFAULT = 'SERVICE_DEFAULT';

    public const ROUTE_OVERRIDE = 'ROUTE_OVERRIDE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APP_DEFAULT,
            self::SERVICE_DEFAULT,
            self::ROUTE_OVERRIDE
        ];
    }
}


