<?php
/**
 * NewAppRouteInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;

use \ArrayAccess;
use \Wodby\Api\ObjectSerializer;

/**
 * NewAppRouteInput Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NewAppRouteInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NewAppRouteInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'app_service_id' => 'int',
        'main' => 'bool',
        'primary' => 'bool',
        'port' => 'int',
        'host' => 'string',
        'path' => 'string',
        'path_type' => 'string',
        'action' => 'string',
        'redirect_scheme' => 'string',
        'redirect_host' => 'string',
        'redirect_path' => 'string',
        'redirect_status_code' => 'int',
        'letsencrypt' => 'bool',
        'auth_login' => 'string',
        'auth_password' => 'string',
        'auth_id' => 'int',
        'options' => '\Wodby\Api\Model\AppEndpointOptionInput[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'app_service_id' => null,
        'main' => null,
        'primary' => null,
        'port' => null,
        'host' => null,
        'path' => null,
        'path_type' => null,
        'action' => null,
        'redirect_scheme' => null,
        'redirect_host' => null,
        'redirect_path' => null,
        'redirect_status_code' => null,
        'letsencrypt' => null,
        'auth_login' => null,
        'auth_password' => null,
        'auth_id' => null,
        'options' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'app_service_id' => false,
        'main' => false,
        'primary' => false,
        'port' => false,
        'host' => false,
        'path' => true,
        'path_type' => true,
        'action' => true,
        'redirect_scheme' => true,
        'redirect_host' => true,
        'redirect_path' => true,
        'redirect_status_code' => true,
        'letsencrypt' => true,
        'auth_login' => true,
        'auth_password' => true,
        'auth_id' => true,
        'options' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'app_service_id' => 'appServiceID',
        'main' => 'main',
        'primary' => 'primary',
        'port' => 'port',
        'host' => 'host',
        'path' => 'path',
        'path_type' => 'pathType',
        'action' => 'action',
        'redirect_scheme' => 'redirectScheme',
        'redirect_host' => 'redirectHost',
        'redirect_path' => 'redirectPath',
        'redirect_status_code' => 'redirectStatusCode',
        'letsencrypt' => 'letsencrypt',
        'auth_login' => 'authLogin',
        'auth_password' => 'authPassword',
        'auth_id' => 'authID',
        'options' => 'options'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'app_service_id' => 'setAppServiceId',
        'main' => 'setMain',
        'primary' => 'setPrimary',
        'port' => 'setPort',
        'host' => 'setHost',
        'path' => 'setPath',
        'path_type' => 'setPathType',
        'action' => 'setAction',
        'redirect_scheme' => 'setRedirectScheme',
        'redirect_host' => 'setRedirectHost',
        'redirect_path' => 'setRedirectPath',
        'redirect_status_code' => 'setRedirectStatusCode',
        'letsencrypt' => 'setLetsencrypt',
        'auth_login' => 'setAuthLogin',
        'auth_password' => 'setAuthPassword',
        'auth_id' => 'setAuthId',
        'options' => 'setOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'app_service_id' => 'getAppServiceId',
        'main' => 'getMain',
        'primary' => 'getPrimary',
        'port' => 'getPort',
        'host' => 'getHost',
        'path' => 'getPath',
        'path_type' => 'getPathType',
        'action' => 'getAction',
        'redirect_scheme' => 'getRedirectScheme',
        'redirect_host' => 'getRedirectHost',
        'redirect_path' => 'getRedirectPath',
        'redirect_status_code' => 'getRedirectStatusCode',
        'letsencrypt' => 'getLetsencrypt',
        'auth_login' => 'getAuthLogin',
        'auth_password' => 'getAuthPassword',
        'auth_id' => 'getAuthId',
        'options' => 'getOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PATH_TYPE_PREFIX = 'PREFIX';
    public const PATH_TYPE_EXACT = 'EXACT';
    public const ACTION_BACKEND = 'BACKEND';
    public const ACTION_REDIRECT = 'REDIRECT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPathTypeAllowableValues()
    {
        return [
            self::PATH_TYPE_PREFIX,
            self::PATH_TYPE_EXACT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionAllowableValues()
    {
        return [
            self::ACTION_BACKEND,
            self::ACTION_REDIRECT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('app_service_id', $data ?? [], null);
        $this->setIfExists('main', $data ?? [], null);
        $this->setIfExists('primary', $data ?? [], null);
        $this->setIfExists('port', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('path_type', $data ?? [], null);
        $this->setIfExists('action', $data ?? [], null);
        $this->setIfExists('redirect_scheme', $data ?? [], null);
        $this->setIfExists('redirect_host', $data ?? [], null);
        $this->setIfExists('redirect_path', $data ?? [], null);
        $this->setIfExists('redirect_status_code', $data ?? [], null);
        $this->setIfExists('letsencrypt', $data ?? [], null);
        $this->setIfExists('auth_login', $data ?? [], null);
        $this->setIfExists('auth_password', $data ?? [], null);
        $this->setIfExists('auth_id', $data ?? [], null);
        $this->setIfExists('options', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['app_service_id'] === null) {
            $invalidProperties[] = "'app_service_id' can't be null";
        }
        if ($this->container['main'] === null) {
            $invalidProperties[] = "'main' can't be null";
        }
        if ($this->container['primary'] === null) {
            $invalidProperties[] = "'primary' can't be null";
        }
        if ($this->container['port'] === null) {
            $invalidProperties[] = "'port' can't be null";
        }
        if ($this->container['host'] === null) {
            $invalidProperties[] = "'host' can't be null";
        }
        $allowedValues = $this->getPathTypeAllowableValues();
        if (!is_null($this->container['path_type']) && !in_array($this->container['path_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'path_type', must be one of '%s'",
                $this->container['path_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($this->container['action']) && !in_array($this->container['action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'action', must be one of '%s'",
                $this->container['action'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets app_service_id
     *
     * @return int
     */
    public function getAppServiceId()
    {
        return $this->container['app_service_id'];
    }

    /**
     * Sets app_service_id
     *
     * @param int $app_service_id app_service_id
     *
     * @return self
     */
    public function setAppServiceId($app_service_id)
    {
        if (is_null($app_service_id)) {
            throw new \InvalidArgumentException('non-nullable app_service_id cannot be null');
        }
        $this->container['app_service_id'] = $app_service_id;

        return $this;
    }

    /**
     * Gets main
     *
     * @return bool
     */
    public function getMain()
    {
        return $this->container['main'];
    }

    /**
     * Sets main
     *
     * @param bool $main main
     *
     * @return self
     */
    public function setMain($main)
    {
        if (is_null($main)) {
            throw new \InvalidArgumentException('non-nullable main cannot be null');
        }
        $this->container['main'] = $main;

        return $this;
    }

    /**
     * Gets primary
     *
     * @return bool
     */
    public function getPrimary()
    {
        return $this->container['primary'];
    }

    /**
     * Sets primary
     *
     * @param bool $primary primary
     *
     * @return self
     */
    public function setPrimary($primary)
    {
        if (is_null($primary)) {
            throw new \InvalidArgumentException('non-nullable primary cannot be null');
        }
        $this->container['primary'] = $primary;

        return $this;
    }

    /**
     * Gets port
     *
     * @return int
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param int $port port
     *
     * @return self
     */
    public function setPort($port)
    {
        if (is_null($port)) {
            throw new \InvalidArgumentException('non-nullable port cannot be null');
        }
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string $host host
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            throw new \InvalidArgumentException('non-nullable host cannot be null');
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path path
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            array_push($this->openAPINullablesSetToNull, 'path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets path_type
     *
     * @return string|null
     */
    public function getPathType()
    {
        return $this->container['path_type'];
    }

    /**
     * Sets path_type
     *
     * @param string|null $path_type path_type
     *
     * @return self
     */
    public function setPathType($path_type)
    {
        if (is_null($path_type)) {
            array_push($this->openAPINullablesSetToNull, 'path_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('path_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getPathTypeAllowableValues();
        if (!is_null($path_type) && !in_array($path_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'path_type', must be one of '%s'",
                    $path_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['path_type'] = $path_type;

        return $this;
    }

    /**
     * Gets action
     *
     * @return string|null
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string|null $action action
     *
     * @return self
     */
    public function setAction($action)
    {
        if (is_null($action)) {
            array_push($this->openAPINullablesSetToNull, 'action');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('action', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($action) && !in_array($action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'action', must be one of '%s'",
                    $action,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets redirect_scheme
     *
     * @return string|null
     */
    public function getRedirectScheme()
    {
        return $this->container['redirect_scheme'];
    }

    /**
     * Sets redirect_scheme
     *
     * @param string|null $redirect_scheme redirect_scheme
     *
     * @return self
     */
    public function setRedirectScheme($redirect_scheme)
    {
        if (is_null($redirect_scheme)) {
            array_push($this->openAPINullablesSetToNull, 'redirect_scheme');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redirect_scheme', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redirect_scheme'] = $redirect_scheme;

        return $this;
    }

    /**
     * Gets redirect_host
     *
     * @return string|null
     */
    public function getRedirectHost()
    {
        return $this->container['redirect_host'];
    }

    /**
     * Sets redirect_host
     *
     * @param string|null $redirect_host redirect_host
     *
     * @return self
     */
    public function setRedirectHost($redirect_host)
    {
        if (is_null($redirect_host)) {
            array_push($this->openAPINullablesSetToNull, 'redirect_host');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redirect_host', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redirect_host'] = $redirect_host;

        return $this;
    }

    /**
     * Gets redirect_path
     *
     * @return string|null
     */
    public function getRedirectPath()
    {
        return $this->container['redirect_path'];
    }

    /**
     * Sets redirect_path
     *
     * @param string|null $redirect_path redirect_path
     *
     * @return self
     */
    public function setRedirectPath($redirect_path)
    {
        if (is_null($redirect_path)) {
            array_push($this->openAPINullablesSetToNull, 'redirect_path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redirect_path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redirect_path'] = $redirect_path;

        return $this;
    }

    /**
     * Gets redirect_status_code
     *
     * @return int|null
     */
    public function getRedirectStatusCode()
    {
        return $this->container['redirect_status_code'];
    }

    /**
     * Sets redirect_status_code
     *
     * @param int|null $redirect_status_code redirect_status_code
     *
     * @return self
     */
    public function setRedirectStatusCode($redirect_status_code)
    {
        if (is_null($redirect_status_code)) {
            array_push($this->openAPINullablesSetToNull, 'redirect_status_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redirect_status_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redirect_status_code'] = $redirect_status_code;

        return $this;
    }

    /**
     * Gets letsencrypt
     *
     * @return bool|null
     */
    public function getLetsencrypt()
    {
        return $this->container['letsencrypt'];
    }

    /**
     * Sets letsencrypt
     *
     * @param bool|null $letsencrypt letsencrypt
     *
     * @return self
     */
    public function setLetsencrypt($letsencrypt)
    {
        if (is_null($letsencrypt)) {
            array_push($this->openAPINullablesSetToNull, 'letsencrypt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('letsencrypt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['letsencrypt'] = $letsencrypt;

        return $this;
    }

    /**
     * Gets auth_login
     *
     * @return string|null
     */
    public function getAuthLogin()
    {
        return $this->container['auth_login'];
    }

    /**
     * Sets auth_login
     *
     * @param string|null $auth_login auth_login
     *
     * @return self
     */
    public function setAuthLogin($auth_login)
    {
        if (is_null($auth_login)) {
            array_push($this->openAPINullablesSetToNull, 'auth_login');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_login', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_login'] = $auth_login;

        return $this;
    }

    /**
     * Gets auth_password
     *
     * @return string|null
     */
    public function getAuthPassword()
    {
        return $this->container['auth_password'];
    }

    /**
     * Sets auth_password
     *
     * @param string|null $auth_password auth_password
     *
     * @return self
     */
    public function setAuthPassword($auth_password)
    {
        if (is_null($auth_password)) {
            array_push($this->openAPINullablesSetToNull, 'auth_password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_password'] = $auth_password;

        return $this;
    }

    /**
     * Gets auth_id
     *
     * @return int|null
     */
    public function getAuthId()
    {
        return $this->container['auth_id'];
    }

    /**
     * Sets auth_id
     *
     * @param int|null $auth_id auth_id
     *
     * @return self
     */
    public function setAuthId($auth_id)
    {
        if (is_null($auth_id)) {
            array_push($this->openAPINullablesSetToNull, 'auth_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_id'] = $auth_id;

        return $this;
    }

    /**
     * Gets options
     *
     * @return \Wodby\Api\Model\AppEndpointOptionInput[]|null
     */
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \Wodby\Api\Model\AppEndpointOptionInput[]|null $options options
     *
     * @return self
     */
    public function setOptions($options)
    {
        if (is_null($options)) {
            throw new \InvalidArgumentException('non-nullable options cannot be null');
        }
        $this->container['options'] = $options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


