<?php
/**
 * NewAppInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;

use \ArrayAccess;
use \Wodby\Api\ObjectSerializer;

/**
 * NewAppInput Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NewAppInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NewAppInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'org_id' => 'int',
        'name' => 'string',
        'title' => 'string',
        'instance_name' => 'string',
        'instance_title' => 'string',
        'domain' => 'string',
        'project_id' => 'int',
        'stack_rev_id' => 'int',
        'services' => '\Wodby\Api\Model\NewAppServiceInput[]',
        'cluster_id' => 'int',
        'env_id' => 'int',
        'ci_integration_id' => 'int',
        'registry_integration_id' => 'int',
        'settings' => '\Wodby\Api\Model\AppInstanceSettingsInput'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'org_id' => null,
        'name' => null,
        'title' => null,
        'instance_name' => null,
        'instance_title' => null,
        'domain' => null,
        'project_id' => null,
        'stack_rev_id' => null,
        'services' => null,
        'cluster_id' => null,
        'env_id' => null,
        'ci_integration_id' => null,
        'registry_integration_id' => null,
        'settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'org_id' => false,
        'name' => false,
        'title' => false,
        'instance_name' => false,
        'instance_title' => false,
        'domain' => false,
        'project_id' => true,
        'stack_rev_id' => false,
        'services' => false,
        'cluster_id' => true,
        'env_id' => false,
        'ci_integration_id' => true,
        'registry_integration_id' => true,
        'settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'org_id' => 'orgId',
        'name' => 'name',
        'title' => 'title',
        'instance_name' => 'instanceName',
        'instance_title' => 'instanceTitle',
        'domain' => 'domain',
        'project_id' => 'projectId',
        'stack_rev_id' => 'stackRevId',
        'services' => 'services',
        'cluster_id' => 'clusterId',
        'env_id' => 'envId',
        'ci_integration_id' => 'ciIntegrationId',
        'registry_integration_id' => 'registryIntegrationId',
        'settings' => 'settings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'org_id' => 'setOrgId',
        'name' => 'setName',
        'title' => 'setTitle',
        'instance_name' => 'setInstanceName',
        'instance_title' => 'setInstanceTitle',
        'domain' => 'setDomain',
        'project_id' => 'setProjectId',
        'stack_rev_id' => 'setStackRevId',
        'services' => 'setServices',
        'cluster_id' => 'setClusterId',
        'env_id' => 'setEnvId',
        'ci_integration_id' => 'setCiIntegrationId',
        'registry_integration_id' => 'setRegistryIntegrationId',
        'settings' => 'setSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'org_id' => 'getOrgId',
        'name' => 'getName',
        'title' => 'getTitle',
        'instance_name' => 'getInstanceName',
        'instance_title' => 'getInstanceTitle',
        'domain' => 'getDomain',
        'project_id' => 'getProjectId',
        'stack_rev_id' => 'getStackRevId',
        'services' => 'getServices',
        'cluster_id' => 'getClusterId',
        'env_id' => 'getEnvId',
        'ci_integration_id' => 'getCiIntegrationId',
        'registry_integration_id' => 'getRegistryIntegrationId',
        'settings' => 'getSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('org_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('instance_name', $data ?? [], null);
        $this->setIfExists('instance_title', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('stack_rev_id', $data ?? [], null);
        $this->setIfExists('services', $data ?? [], null);
        $this->setIfExists('cluster_id', $data ?? [], null);
        $this->setIfExists('env_id', $data ?? [], null);
        $this->setIfExists('ci_integration_id', $data ?? [], null);
        $this->setIfExists('registry_integration_id', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['instance_name'] === null) {
            $invalidProperties[] = "'instance_name' can't be null";
        }
        if ($this->container['stack_rev_id'] === null) {
            $invalidProperties[] = "'stack_rev_id' can't be null";
        }
        if ($this->container['env_id'] === null) {
            $invalidProperties[] = "'env_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets org_id
     *
     * @return int|null
     */
    public function getOrgId()
    {
        return $this->container['org_id'];
    }

    /**
     * Sets org_id
     *
     * @param int|null $org_id Optional for API-key requests; defaults to the API key's organization.
     *
     * @return self
     */
    public function setOrgId($org_id)
    {
        if (is_null($org_id)) {
            throw new \InvalidArgumentException('non-nullable org_id cannot be null');
        }
        $this->container['org_id'] = $org_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Defaults to name when omitted.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets instance_name
     *
     * @return string
     */
    public function getInstanceName()
    {
        return $this->container['instance_name'];
    }

    /**
     * Sets instance_name
     *
     * @param string $instance_name instance_name
     *
     * @return self
     */
    public function setInstanceName($instance_name)
    {
        if (is_null($instance_name)) {
            throw new \InvalidArgumentException('non-nullable instance_name cannot be null');
        }
        $this->container['instance_name'] = $instance_name;

        return $this;
    }

    /**
     * Gets instance_title
     *
     * @return string|null
     */
    public function getInstanceTitle()
    {
        return $this->container['instance_title'];
    }

    /**
     * Sets instance_title
     *
     * @param string|null $instance_title Defaults to instanceName when omitted.
     *
     * @return self
     */
    public function setInstanceTitle($instance_title)
    {
        if (is_null($instance_title)) {
            throw new \InvalidArgumentException('non-nullable instance_title cannot be null');
        }
        $this->container['instance_title'] = $instance_title;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain Defaults to instanceName.name.orgDomain when omitted.
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return int|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param int|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            array_push($this->openAPINullablesSetToNull, 'project_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('project_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets stack_rev_id
     *
     * @return int
     */
    public function getStackRevId()
    {
        return $this->container['stack_rev_id'];
    }

    /**
     * Sets stack_rev_id
     *
     * @param int $stack_rev_id stack_rev_id
     *
     * @return self
     */
    public function setStackRevId($stack_rev_id)
    {
        if (is_null($stack_rev_id)) {
            throw new \InvalidArgumentException('non-nullable stack_rev_id cannot be null');
        }
        $this->container['stack_rev_id'] = $stack_rev_id;

        return $this;
    }

    /**
     * Gets services
     *
     * @return \Wodby\Api\Model\NewAppServiceInput[]|null
     */
    public function getServices()
    {
        return $this->container['services'];
    }

    /**
     * Sets services
     *
     * @param \Wodby\Api\Model\NewAppServiceInput[]|null $services Defaults to the stack revision's service defaults when omitted.
     *
     * @return self
     */
    public function setServices($services)
    {
        if (is_null($services)) {
            throw new \InvalidArgumentException('non-nullable services cannot be null');
        }
        $this->container['services'] = $services;

        return $this;
    }

    /**
     * Gets cluster_id
     *
     * @return int|null
     */
    public function getClusterId()
    {
        return $this->container['cluster_id'];
    }

    /**
     * Sets cluster_id
     *
     * @param int|null $cluster_id cluster_id
     *
     * @return self
     */
    public function setClusterId($cluster_id)
    {
        if (is_null($cluster_id)) {
            array_push($this->openAPINullablesSetToNull, 'cluster_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cluster_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cluster_id'] = $cluster_id;

        return $this;
    }

    /**
     * Gets env_id
     *
     * @return int
     */
    public function getEnvId()
    {
        return $this->container['env_id'];
    }

    /**
     * Sets env_id
     *
     * @param int $env_id env_id
     *
     * @return self
     */
    public function setEnvId($env_id)
    {
        if (is_null($env_id)) {
            throw new \InvalidArgumentException('non-nullable env_id cannot be null');
        }
        $this->container['env_id'] = $env_id;

        return $this;
    }

    /**
     * Gets ci_integration_id
     *
     * @return int|null
     */
    public function getCiIntegrationId()
    {
        return $this->container['ci_integration_id'];
    }

    /**
     * Sets ci_integration_id
     *
     * @param int|null $ci_integration_id ci_integration_id
     *
     * @return self
     */
    public function setCiIntegrationId($ci_integration_id)
    {
        if (is_null($ci_integration_id)) {
            array_push($this->openAPINullablesSetToNull, 'ci_integration_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ci_integration_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ci_integration_id'] = $ci_integration_id;

        return $this;
    }

    /**
     * Gets registry_integration_id
     *
     * @return int|null
     */
    public function getRegistryIntegrationId()
    {
        return $this->container['registry_integration_id'];
    }

    /**
     * Sets registry_integration_id
     *
     * @param int|null $registry_integration_id registry_integration_id
     *
     * @return self
     */
    public function setRegistryIntegrationId($registry_integration_id)
    {
        if (is_null($registry_integration_id)) {
            array_push($this->openAPINullablesSetToNull, 'registry_integration_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('registry_integration_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['registry_integration_id'] = $registry_integration_id;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \Wodby\Api\Model\AppInstanceSettingsInput|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \Wodby\Api\Model\AppInstanceSettingsInput|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            throw new \InvalidArgumentException('non-nullable settings cannot be null');
        }
        $this->container['settings'] = $settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


