<?php
/**
 * OrgCapabilities
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;

use \ArrayAccess;
use \Wodby\Api\ObjectSerializer;

/**
 * OrgCapabilities Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrgCapabilities implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrgCapabilities';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'custom_domains' => 'bool',
        'auto_backups' => 'bool',
        'users' => 'bool',
        'projects' => 'bool',
        'cron_schedules' => 'bool',
        'autoscale' => 'bool',
        'app_instance_pause' => 'bool',
        'web_shell' => 'bool',
        'wodby_cloud' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'custom_domains' => null,
        'auto_backups' => null,
        'users' => null,
        'projects' => null,
        'cron_schedules' => null,
        'autoscale' => null,
        'app_instance_pause' => null,
        'web_shell' => null,
        'wodby_cloud' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'custom_domains' => false,
        'auto_backups' => false,
        'users' => false,
        'projects' => false,
        'cron_schedules' => false,
        'autoscale' => false,
        'app_instance_pause' => false,
        'web_shell' => false,
        'wodby_cloud' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'custom_domains' => 'customDomains',
        'auto_backups' => 'autoBackups',
        'users' => 'users',
        'projects' => 'projects',
        'cron_schedules' => 'cronSchedules',
        'autoscale' => 'autoscale',
        'app_instance_pause' => 'appInstancePause',
        'web_shell' => 'webShell',
        'wodby_cloud' => 'wodbyCloud'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'custom_domains' => 'setCustomDomains',
        'auto_backups' => 'setAutoBackups',
        'users' => 'setUsers',
        'projects' => 'setProjects',
        'cron_schedules' => 'setCronSchedules',
        'autoscale' => 'setAutoscale',
        'app_instance_pause' => 'setAppInstancePause',
        'web_shell' => 'setWebShell',
        'wodby_cloud' => 'setWodbyCloud'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'custom_domains' => 'getCustomDomains',
        'auto_backups' => 'getAutoBackups',
        'users' => 'getUsers',
        'projects' => 'getProjects',
        'cron_schedules' => 'getCronSchedules',
        'autoscale' => 'getAutoscale',
        'app_instance_pause' => 'getAppInstancePause',
        'web_shell' => 'getWebShell',
        'wodby_cloud' => 'getWodbyCloud'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('custom_domains', $data ?? [], null);
        $this->setIfExists('auto_backups', $data ?? [], null);
        $this->setIfExists('users', $data ?? [], null);
        $this->setIfExists('projects', $data ?? [], null);
        $this->setIfExists('cron_schedules', $data ?? [], null);
        $this->setIfExists('autoscale', $data ?? [], null);
        $this->setIfExists('app_instance_pause', $data ?? [], null);
        $this->setIfExists('web_shell', $data ?? [], null);
        $this->setIfExists('wodby_cloud', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['custom_domains'] === null) {
            $invalidProperties[] = "'custom_domains' can't be null";
        }
        if ($this->container['auto_backups'] === null) {
            $invalidProperties[] = "'auto_backups' can't be null";
        }
        if ($this->container['users'] === null) {
            $invalidProperties[] = "'users' can't be null";
        }
        if ($this->container['projects'] === null) {
            $invalidProperties[] = "'projects' can't be null";
        }
        if ($this->container['cron_schedules'] === null) {
            $invalidProperties[] = "'cron_schedules' can't be null";
        }
        if ($this->container['autoscale'] === null) {
            $invalidProperties[] = "'autoscale' can't be null";
        }
        if ($this->container['app_instance_pause'] === null) {
            $invalidProperties[] = "'app_instance_pause' can't be null";
        }
        if ($this->container['web_shell'] === null) {
            $invalidProperties[] = "'web_shell' can't be null";
        }
        if ($this->container['wodby_cloud'] === null) {
            $invalidProperties[] = "'wodby_cloud' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets custom_domains
     *
     * @return bool
     */
    public function getCustomDomains()
    {
        return $this->container['custom_domains'];
    }

    /**
     * Sets custom_domains
     *
     * @param bool $custom_domains custom_domains
     *
     * @return self
     */
    public function setCustomDomains($custom_domains)
    {
        if (is_null($custom_domains)) {
            throw new \InvalidArgumentException('non-nullable custom_domains cannot be null');
        }
        $this->container['custom_domains'] = $custom_domains;

        return $this;
    }

    /**
     * Gets auto_backups
     *
     * @return bool
     */
    public function getAutoBackups()
    {
        return $this->container['auto_backups'];
    }

    /**
     * Sets auto_backups
     *
     * @param bool $auto_backups auto_backups
     *
     * @return self
     */
    public function setAutoBackups($auto_backups)
    {
        if (is_null($auto_backups)) {
            throw new \InvalidArgumentException('non-nullable auto_backups cannot be null');
        }
        $this->container['auto_backups'] = $auto_backups;

        return $this;
    }

    /**
     * Gets users
     *
     * @return bool
     */
    public function getUsers()
    {
        return $this->container['users'];
    }

    /**
     * Sets users
     *
     * @param bool $users users
     *
     * @return self
     */
    public function setUsers($users)
    {
        if (is_null($users)) {
            throw new \InvalidArgumentException('non-nullable users cannot be null');
        }
        $this->container['users'] = $users;

        return $this;
    }

    /**
     * Gets projects
     *
     * @return bool
     */
    public function getProjects()
    {
        return $this->container['projects'];
    }

    /**
     * Sets projects
     *
     * @param bool $projects projects
     *
     * @return self
     */
    public function setProjects($projects)
    {
        if (is_null($projects)) {
            throw new \InvalidArgumentException('non-nullable projects cannot be null');
        }
        $this->container['projects'] = $projects;

        return $this;
    }

    /**
     * Gets cron_schedules
     *
     * @return bool
     */
    public function getCronSchedules()
    {
        return $this->container['cron_schedules'];
    }

    /**
     * Sets cron_schedules
     *
     * @param bool $cron_schedules cron_schedules
     *
     * @return self
     */
    public function setCronSchedules($cron_schedules)
    {
        if (is_null($cron_schedules)) {
            throw new \InvalidArgumentException('non-nullable cron_schedules cannot be null');
        }
        $this->container['cron_schedules'] = $cron_schedules;

        return $this;
    }

    /**
     * Gets autoscale
     *
     * @return bool
     */
    public function getAutoscale()
    {
        return $this->container['autoscale'];
    }

    /**
     * Sets autoscale
     *
     * @param bool $autoscale autoscale
     *
     * @return self
     */
    public function setAutoscale($autoscale)
    {
        if (is_null($autoscale)) {
            throw new \InvalidArgumentException('non-nullable autoscale cannot be null');
        }
        $this->container['autoscale'] = $autoscale;

        return $this;
    }

    /**
     * Gets app_instance_pause
     *
     * @return bool
     */
    public function getAppInstancePause()
    {
        return $this->container['app_instance_pause'];
    }

    /**
     * Sets app_instance_pause
     *
     * @param bool $app_instance_pause app_instance_pause
     *
     * @return self
     */
    public function setAppInstancePause($app_instance_pause)
    {
        if (is_null($app_instance_pause)) {
            throw new \InvalidArgumentException('non-nullable app_instance_pause cannot be null');
        }
        $this->container['app_instance_pause'] = $app_instance_pause;

        return $this;
    }

    /**
     * Gets web_shell
     *
     * @return bool
     */
    public function getWebShell()
    {
        return $this->container['web_shell'];
    }

    /**
     * Sets web_shell
     *
     * @param bool $web_shell web_shell
     *
     * @return self
     */
    public function setWebShell($web_shell)
    {
        if (is_null($web_shell)) {
            throw new \InvalidArgumentException('non-nullable web_shell cannot be null');
        }
        $this->container['web_shell'] = $web_shell;

        return $this;
    }

    /**
     * Gets wodby_cloud
     *
     * @return bool
     */
    public function getWodbyCloud()
    {
        return $this->container['wodby_cloud'];
    }

    /**
     * Sets wodby_cloud
     *
     * @param bool $wodby_cloud wodby_cloud
     *
     * @return self
     */
    public function setWodbyCloud($wodby_cloud)
    {
        if (is_null($wodby_cloud)) {
            throw new \InvalidArgumentException('non-nullable wodby_cloud cannot be null');
        }
        $this->container['wodby_cloud'] = $wodby_cloud;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


