<?php
/**
 * StackService
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wodby 2.0 Public API
 *
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Wodby\Api\Model;

use \ArrayAccess;
use \Wodby\Api\ObjectSerializer;

/**
 * StackService Class Doc Comment
 *
 * @category Class
 * @package  Wodby\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StackService implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StackService';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'title' => 'string',
        'type' => 'string',
        'main' => 'bool',
        'disabled' => 'bool',
        'required' => 'bool',
        'replicas' => 'int',
        'service_rev_id' => 'int',
        'service_rev_name' => 'string',
        'service_rev_title' => 'string',
        'service_rev_version' => 'string',
        'build_source_integration_id' => 'int',
        'build_source_remote_repo_id' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'title' => null,
        'type' => null,
        'main' => null,
        'disabled' => null,
        'required' => null,
        'replicas' => null,
        'service_rev_id' => null,
        'service_rev_name' => null,
        'service_rev_title' => null,
        'service_rev_version' => null,
        'build_source_integration_id' => null,
        'build_source_remote_repo_id' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'title' => false,
        'type' => false,
        'main' => false,
        'disabled' => false,
        'required' => false,
        'replicas' => false,
        'service_rev_id' => false,
        'service_rev_name' => false,
        'service_rev_title' => false,
        'service_rev_version' => false,
        'build_source_integration_id' => true,
        'build_source_remote_repo_id' => true,
        'created_at' => false,
        'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'title' => 'title',
        'type' => 'type',
        'main' => 'main',
        'disabled' => 'disabled',
        'required' => 'required',
        'replicas' => 'replicas',
        'service_rev_id' => 'serviceRevId',
        'service_rev_name' => 'serviceRevName',
        'service_rev_title' => 'serviceRevTitle',
        'service_rev_version' => 'serviceRevVersion',
        'build_source_integration_id' => 'buildSourceIntegrationId',
        'build_source_remote_repo_id' => 'buildSourceRemoteRepoId',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'title' => 'setTitle',
        'type' => 'setType',
        'main' => 'setMain',
        'disabled' => 'setDisabled',
        'required' => 'setRequired',
        'replicas' => 'setReplicas',
        'service_rev_id' => 'setServiceRevId',
        'service_rev_name' => 'setServiceRevName',
        'service_rev_title' => 'setServiceRevTitle',
        'service_rev_version' => 'setServiceRevVersion',
        'build_source_integration_id' => 'setBuildSourceIntegrationId',
        'build_source_remote_repo_id' => 'setBuildSourceRemoteRepoId',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'title' => 'getTitle',
        'type' => 'getType',
        'main' => 'getMain',
        'disabled' => 'getDisabled',
        'required' => 'getRequired',
        'replicas' => 'getReplicas',
        'service_rev_id' => 'getServiceRevId',
        'service_rev_name' => 'getServiceRevName',
        'service_rev_title' => 'getServiceRevTitle',
        'service_rev_version' => 'getServiceRevVersion',
        'build_source_integration_id' => 'getBuildSourceIntegrationId',
        'build_source_remote_repo_id' => 'getBuildSourceRemoteRepoId',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('main', $data ?? [], null);
        $this->setIfExists('disabled', $data ?? [], null);
        $this->setIfExists('required', $data ?? [], null);
        $this->setIfExists('replicas', $data ?? [], null);
        $this->setIfExists('service_rev_id', $data ?? [], null);
        $this->setIfExists('service_rev_name', $data ?? [], null);
        $this->setIfExists('service_rev_title', $data ?? [], null);
        $this->setIfExists('service_rev_version', $data ?? [], null);
        $this->setIfExists('build_source_integration_id', $data ?? [], null);
        $this->setIfExists('build_source_remote_repo_id', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['main'] === null) {
            $invalidProperties[] = "'main' can't be null";
        }
        if ($this->container['disabled'] === null) {
            $invalidProperties[] = "'disabled' can't be null";
        }
        if ($this->container['required'] === null) {
            $invalidProperties[] = "'required' can't be null";
        }
        if ($this->container['replicas'] === null) {
            $invalidProperties[] = "'replicas' can't be null";
        }
        if ($this->container['service_rev_id'] === null) {
            $invalidProperties[] = "'service_rev_id' can't be null";
        }
        if ($this->container['service_rev_name'] === null) {
            $invalidProperties[] = "'service_rev_name' can't be null";
        }
        if ($this->container['service_rev_title'] === null) {
            $invalidProperties[] = "'service_rev_title' can't be null";
        }
        if ($this->container['service_rev_version'] === null) {
            $invalidProperties[] = "'service_rev_version' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets main
     *
     * @return bool
     */
    public function getMain()
    {
        return $this->container['main'];
    }

    /**
     * Sets main
     *
     * @param bool $main main
     *
     * @return self
     */
    public function setMain($main)
    {
        if (is_null($main)) {
            throw new \InvalidArgumentException('non-nullable main cannot be null');
        }
        $this->container['main'] = $main;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool $disabled disabled
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }

    /**
     * Gets required
     *
     * @return bool
     */
    public function getRequired()
    {
        return $this->container['required'];
    }

    /**
     * Sets required
     *
     * @param bool $required required
     *
     * @return self
     */
    public function setRequired($required)
    {
        if (is_null($required)) {
            throw new \InvalidArgumentException('non-nullable required cannot be null');
        }
        $this->container['required'] = $required;

        return $this;
    }

    /**
     * Gets replicas
     *
     * @return int
     */
    public function getReplicas()
    {
        return $this->container['replicas'];
    }

    /**
     * Sets replicas
     *
     * @param int $replicas replicas
     *
     * @return self
     */
    public function setReplicas($replicas)
    {
        if (is_null($replicas)) {
            throw new \InvalidArgumentException('non-nullable replicas cannot be null');
        }
        $this->container['replicas'] = $replicas;

        return $this;
    }

    /**
     * Gets service_rev_id
     *
     * @return int
     */
    public function getServiceRevId()
    {
        return $this->container['service_rev_id'];
    }

    /**
     * Sets service_rev_id
     *
     * @param int $service_rev_id service_rev_id
     *
     * @return self
     */
    public function setServiceRevId($service_rev_id)
    {
        if (is_null($service_rev_id)) {
            throw new \InvalidArgumentException('non-nullable service_rev_id cannot be null');
        }
        $this->container['service_rev_id'] = $service_rev_id;

        return $this;
    }

    /**
     * Gets service_rev_name
     *
     * @return string
     */
    public function getServiceRevName()
    {
        return $this->container['service_rev_name'];
    }

    /**
     * Sets service_rev_name
     *
     * @param string $service_rev_name service_rev_name
     *
     * @return self
     */
    public function setServiceRevName($service_rev_name)
    {
        if (is_null($service_rev_name)) {
            throw new \InvalidArgumentException('non-nullable service_rev_name cannot be null');
        }
        $this->container['service_rev_name'] = $service_rev_name;

        return $this;
    }

    /**
     * Gets service_rev_title
     *
     * @return string
     */
    public function getServiceRevTitle()
    {
        return $this->container['service_rev_title'];
    }

    /**
     * Sets service_rev_title
     *
     * @param string $service_rev_title service_rev_title
     *
     * @return self
     */
    public function setServiceRevTitle($service_rev_title)
    {
        if (is_null($service_rev_title)) {
            throw new \InvalidArgumentException('non-nullable service_rev_title cannot be null');
        }
        $this->container['service_rev_title'] = $service_rev_title;

        return $this;
    }

    /**
     * Gets service_rev_version
     *
     * @return string
     */
    public function getServiceRevVersion()
    {
        return $this->container['service_rev_version'];
    }

    /**
     * Sets service_rev_version
     *
     * @param string $service_rev_version service_rev_version
     *
     * @return self
     */
    public function setServiceRevVersion($service_rev_version)
    {
        if (is_null($service_rev_version)) {
            throw new \InvalidArgumentException('non-nullable service_rev_version cannot be null');
        }
        $this->container['service_rev_version'] = $service_rev_version;

        return $this;
    }

    /**
     * Gets build_source_integration_id
     *
     * @return int|null
     */
    public function getBuildSourceIntegrationId()
    {
        return $this->container['build_source_integration_id'];
    }

    /**
     * Sets build_source_integration_id
     *
     * @param int|null $build_source_integration_id build_source_integration_id
     *
     * @return self
     */
    public function setBuildSourceIntegrationId($build_source_integration_id)
    {
        if (is_null($build_source_integration_id)) {
            array_push($this->openAPINullablesSetToNull, 'build_source_integration_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('build_source_integration_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['build_source_integration_id'] = $build_source_integration_id;

        return $this;
    }

    /**
     * Gets build_source_remote_repo_id
     *
     * @return string|null
     */
    public function getBuildSourceRemoteRepoId()
    {
        return $this->container['build_source_remote_repo_id'];
    }

    /**
     * Sets build_source_remote_repo_id
     *
     * @param string|null $build_source_remote_repo_id build_source_remote_repo_id
     *
     * @return self
     */
    public function setBuildSourceRemoteRepoId($build_source_remote_repo_id)
    {
        if (is_null($build_source_remote_repo_id)) {
            array_push($this->openAPINullablesSetToNull, 'build_source_remote_repo_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('build_source_remote_repo_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['build_source_remote_repo_id'] = $build_source_remote_repo_id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


